server:
  port: 8000
spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.169.182:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    tomcat:
      min-idle: 20
      max-active: 200
      max-wait: 30000
  application:
    name: microservice-simple-provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true